"""Read-only incremental building v004r1 package/coverage/registration audit."""
from pathlib import Path
from PIL import Image
from decimal import Decimal
import numpy as np,json,zipfile,hashlib,re,difflib
ROOT=Path(r'E:/dev/shader/godot-shader/godot-shader-simple');OUT=Path(__file__).parent;PKG=OUT/'package';ZIP=ROOT/'art-source/ember/deliveries/building_assets_v004r1_2026-10-06.zip';OLD=ROOT/'art-source/ember/deliveries/building_assets_v004_2026-10-06.zip';LIVE=ROOT/'art-source/ember/building-assets-v004r1'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def read(p,precise=False):return json.loads(Path(p).read_text(encoding='utf-8-sig'),parse_float=Decimal,parse_int=Decimal) if precise else json.loads(Path(p).read_text(encoding='utf-8-sig'))
def array(p):return np.array(Image.open(p).convert('RGBA'))
def path(s):return PKG/s.removeprefix('res://')
def pixels_diff(a,b):return int(np.count_nonzero(np.any(a!=b,axis=2)))
def visible_diff(a,b):return int(np.count_nonzero((a[:,:,3]!=b[:,:,3])|((a[:,:,3]>0)&np.any(a[:,:,:3]!=b[:,:,:3],axis=2))))
def transparency(a):return {'alpha_values':np.unique(a[:,:,3]).tolist(),'transparent_nonzero_rgb':int(np.count_nonzero((a[:,:,3]==0)&np.any(a[:,:,:3]!=0,axis=2))),'covered_pixels':int(np.count_nonzero(a[:,:,3]))}
def number_leaves(o,p='$'):
 if isinstance(o,Decimal):return {p:str(o.normalize())}
 if isinstance(o,dict):return {q:v for k,n in o.items() for q,v in number_leaves(n,p+'.'+k).items()}
 if isinstance(o,list):return {q:v for i,n in enumerate(o) for q,v in number_leaves(n,p+f'[{i}]').items()}
 return {}
def layer_selection(shape,regions,chamfer):
 selected=np.zeros(shape[:2],dtype=bool)
 for dx,dy,dw,dh in regions:
  dx,dy,dw,dh=map(int,[dx,dy,dw,dh]);ys,xs=np.mgrid[:dh,:dw];px=xs+.5;py=ys+.5;sel=(px+py>=chamfer)&(dw-px+py>=chamfer);selected[dy:dy+dh,dx:dx+dw]|=sel
 return selected
result={'scope':'Independent fixed ZIP, untouched master/reference provenance, binary Alpha/covered RGB and same-source allocation, full-precision geometry and bound producer records. No Godot/GPU rerun.'}
receipt=read(LIVE/'delivery_receipt_v004r1.json');stage=Path(receipt['stage'])
with zipfile.ZipFile(ZIP) as z,zipfile.ZipFile(OLD) as old:
 names=z.namelist();m=json.loads(z.read('DELIVERY_MANIFEST.json'));assert all(not Path(n).is_absolute() and '..' not in Path(n).parts for n in names);z.extractall(PKG)
 checks=[{'path':f['path'],'bytes_match':len(z.read(f['path']))==f['bytes'],'zip_sha_match':hashlib.sha256(z.read(f['path'])).hexdigest()==f['sha256'],'unpacked_sha_match':sha(PKG/f['path'])==f['sha256'],'producer_portable_stage_exists':(stage/f['path']).is_file(),'producer_portable_stage_same':sha(stage/f['path'])==f['sha256'] if (stage/f['path']).is_file() else False} for f in m['files']]
 result['archive']={'sha256':sha(ZIP),'bytes':ZIP.stat().st_size,'entries':len(names),'payloads':len(checks),'duplicates':len(names)-len(set(names)),'crc_failure':z.testzip(),'unlisted':sorted(set(names)-{f['path'] for f in checks}),'checks':checks}
 result['old_zip']={'sha256':sha(OLD),'common_changed':[n for n in sorted(set(names)&set(old.namelist())) if z.read(n)!=old.read(n)],'common_same_count':sum(z.read(n)==old.read(n) for n in set(names)&set(old.namelist())),'removed_paths':sorted(set(old.namelist())-set(names)),'added_paths':sorted(set(names)-set(old.namelist()))}
 original_catalog=json.loads(old.read('assets/ember/building_assets_v004/catalog_v004.json'),parse_float=Decimal,parse_int=Decimal)
 result['unchanged_source_reference_common']=[{'path':n,'byte_identical':z.read(n)==old.read(n)} for n in sorted(set(names)&set(old.namelist())) if '/masters/' in n or '/references/' in n or '/prompts/' in n or n.startswith('scripts/') or n.startswith('shaders/') or n in ['assets/ember/characters/robot/robot_idle_down_v001.png','assets/ember/map_assets_v001/floors/floor_steel_period_v001.png','art-source/ember/selected-buildings-v001/selection_record_v001.json','assets/ember/building_assets_v004/catalog_v004.json']]
 textdiff={n:''.join(difflib.unified_diff(old.read(n).decode('utf-8-sig').splitlines(True),z.read(n).decode('utf-8-sig').splitlines(True),fromfile='v004/'+n,tofile='v004r1/'+n)) for n in ['project.godot','README.md']};(OUT/'portable-text-diff.json').write_text(json.dumps(textdiff,ensure_ascii=False,indent=2),encoding='utf8')
base=PKG/'assets/ember/building_assets_v004r1';cat=read(base/'catalog_v004r1.json');new_precise=read(base/'catalog_v004r1.json',True);func=read(base/'functional_layers_v004r1.json');coverage_records=read(base/'coverage_export_v004r1.json');reg={b['id']:b for b in new_precise['buildings']};oldreg={b['id']:b for b in original_catalog['buildings']}
numbers_old=number_leaves(original_catalog);numbers_new=number_leaves(new_precise);result['exact_numeric_registration']={'old_number_count':len(numbers_old),'new_number_count':len(numbers_new),'all_old_numeric_paths_exist':all(p in numbers_new for p in numbers_old),'changed_numeric_leaves':[{'path':p,'old':v,'new':numbers_new.get(p)} for p,v in numbers_old.items() if numbers_new.get(p)!=v],'new_numeric_leaves':[{p:numbers_new[p]} for p in numbers_new if p not in numbers_old]}
buildings=[];layer_results=[]
for b in cat['buildings']:
 bid=b['id'];source=array(path(b['source_master']));solid=source[:,:,3]>=128;expected=np.zeros_like(source);expected[solid]=source[solid];expected[solid,3]=255;actual=array(path(b['complete_texture']));wantmask=np.zeros_like(source);wantmask[solid]=255;mask=array(path(b['coverage_mask']));f=next(q for q in func['buildings'] if q['building_id']==bid)
 fixed_expected=expected.copy();all_layer_arrays=[];layer_ownership=np.zeros(source.shape[:2],np.int16)
 for l in f['layers']:
  selected=layer_selection(source.shape,l['regions'],l['chamfer']);want=np.zeros_like(source);want[selected]=expected[selected];fixed_expected[selected]=0;have=array(path(l['texture']));layer_ownership+=(have[:,:,3]>0).astype(np.int16);all_layer_arrays.append(have)
  layer_results.append({'building':bid,'layer':l['id'],'sha_matches':sha(path(l['texture']))==l['sha256'],'shape_matches':have.shape==expected.shape,'raw_rgba_difference_vs_independent_assignment':pixels_diff(have,want),'visible_rgba_difference_vs_independent_assignment':visible_diff(have,want),**transparency(have)})
 fixed=array(path(f['fixed_architecture']));layer_ownership+=(fixed[:,:,3]>0).astype(np.int16);combined=np.zeros_like(source)
 for have in [fixed]+all_layer_arrays:covered=have[:,:,3]>0;combined[covered]=have[covered]
 layer_results.append({'building':bid,'layer':'fixed_architecture','sha_matches':sha(path(f['fixed_architecture']))==f['fixed_sha256'],'shape_matches':fixed.shape==expected.shape,'raw_rgba_difference_vs_independent_assignment':pixels_diff(fixed,fixed_expected),'visible_rgba_difference_vs_independent_assignment':visible_diff(fixed,fixed_expected),**transparency(fixed)})
 old=dict(oldreg[bid]);new=dict(reg[bid]);registration_old=number_leaves(old);registration_new=number_leaves(new)
 buildings.append({'building':bid,'master_sha_matches_catalog':sha(path(b['source_master']))==b['source_master_sha256'],'production_sha_matches_catalog':sha(path(b['complete_texture']))==b['complete_sha256'],'mask_sha_matches_catalog':sha(path(b['coverage_mask']))==b['coverage_sha256'],'shape':list(actual.shape),'complete_raw_rgba_diff_vs_source_rule':pixels_diff(actual,expected),'mask_raw_rgba_diff_vs_source_rule':pixels_diff(mask,wantmask),'covered_rgb_channel_differences':int(np.count_nonzero(actual[solid,:3]!=source[solid,:3])),'actual_alpha':transparency(actual),'mask_alpha':transparency(mask),'source_partial_alpha':int(np.count_nonzero((source[:,:,3]>0)&(source[:,:,3]<255))),'discarded_low_alpha':int(np.count_nonzero((source[:,:,3]>0)&(source[:,:,3]<128))),'functional_visible_overlap_pixels':int(np.count_nonzero(layer_ownership>1)),'functional_missing_covered_pixels':int(np.count_nonzero(solid&(layer_ownership==0))),'functional_combined_rgba_diff_canonical_transparent':pixels_diff(combined,actual),'registration_numeric_all_same':registration_old==registration_new,'functional_registration_same':all(funcb[k]==b[k] for funcb in [f] for k in ['canvas_px','source_pivot_px','uniform_scale'])})
result['buildings']=buildings;result['functional_layers']=layer_results
statics=[]
for b in cat['buildings']:
 text=(PKG/f"scenes/ember/building_assets_v004r1/{b['id']}_static.tscn").read_text(encoding='utf8');offset=list(map(Decimal,re.search(r'offset = Vector2\(([^,]+), ([^)]+)\)',text).groups()));scale=list(map(Decimal,re.search(r'scale = Vector2\(([^,]+), ([^)]+)\)',text).groups()));statics.append({'building':b['id'],'texture_matches_catalog':b['complete_texture'] in text,'offset_matches_pivot':offset==[-v for v in reg[b['id']]['source_pivot_px']],'scale_matches_full_precision_catalog':scale==[reg[b['id']]['uniform_scale']]*2,'nearest_and_not_centered':'texture_filter = 1' in text and 'centered = false' in text})
result['static_prefabs']=statics
validation=read(base/'previews/validation_v004r1.json');result['producer_validation_bindings']={'sha256':sha(base/'previews/validation_v004r1.json'),'passed':validation['passed'],'total':validation['total'],'actual_check_entries':len(validation['checks']),'all_author_checks_report_pass':all(c['pass'] for c in validation['checks']),'bindings':[{'path':p,'same_package_sha':sha(PKG/p)==h} for p,h in validation['bindings'].items()],'captures':[{'path':c['path'],'same_package_sha':sha(path(c['path']))==c['sha256'],'kind':c['kind']} for c in validation['captures']],'portable_stage_validation_same':sha(stage/'assets/ember/building_assets_v004r1/previews/validation_v004r1.json')==sha(base/'previews/validation_v004r1.json'),'independent_gpu_rerun':False,'independent_94_behaviour_rerun':False}
baseline=read(ROOT/'art-source/ember/ta-review-v001/ui-v003-integrity/integrity-v003.json');result['historical_protected_workspace']={'baseline':'ui-v003-integrity/integrity-v003.json historical snapshot only','checks':[{'path':c['path'],'baseline_sha256':c['expected'],'current_sha256':sha(ROOT/c['path']),'same':sha(ROOT/c['path'])==c['expected']} for c in baseline['checks'] if c['scope']=='protected_workspace']}
result['external_delivery_receipt']={'sha256':sha(LIVE/'delivery_receipt_v004r1.json'),'zip_sha_matches':receipt['sha256']==sha(ZIP),'bytes_matches':receipt['bytes']==ZIP.stat().st_size,'entries_matches':receipt['entries']==len(names),'payloads_matches':receipt['payload_files']==len(checks),'receipt':receipt}
result['summary']={'manifest_all':all(all(c[k] for k in ['bytes_match','zip_sha_match','unpacked_sha_match']) for c in checks),'complete_png_count':len(buildings),'functional_layer_count':len(layer_results),'production_rgba_differences':sum(b['complete_raw_rgba_diff_vs_source_rule'] for b in buildings),'mask_rgba_differences':sum(b['mask_raw_rgba_diff_vs_source_rule'] for b in buildings),'covered_rgb_channel_differences':sum(b['covered_rgb_channel_differences'] for b in buildings),'functional_visible_rgba_differences':sum(l['visible_rgba_difference_vs_independent_assignment'] for l in layer_results),'functional_raw_rgba_differences':sum(l['raw_rgba_difference_vs_independent_assignment'] for l in layer_results),'combined_rgba_differences':sum(b['functional_combined_rgba_diff_canonical_transparent'] for b in buildings),'numeric_geometry_changed':len(result['exact_numeric_registration']['changed_numeric_leaves']),'hidden_transparent_rgb_exception_layers':len([l for l in layer_results if l['transparent_nonzero_rgb']]),'producer_stage_payload_same':all(c['producer_portable_stage_same'] for c in checks)}
result['summary']['numeric_leaf_differences']=result['summary'].pop('numeric_geometry_changed')
result['summary']['source_geometry_numeric_changes']=sum(not d['path'].endswith('.center_world_x') for d in result['exact_numeric_registration']['changed_numeric_leaves'])
clarification=LIVE/'review_clarifications_v004r1.md'
result['outside_package_clarification']={'path':str(clarification),'sha256':sha(clarification),'fixed_zip_hash_mentioned':sha(ZIP) in clarification.read_text(encoding='utf8'),'scope':'Outside-package wording correction only; does not change fixed PNG, code or manifest.'}
(OUT/'bound-review-clarifications.md').write_text(clarification.read_text(encoding='utf8'),encoding='utf8')
(OUT/'evidence.json').write_text(json.dumps(result,ensure_ascii=False,indent=2),encoding='utf8');print(json.dumps({'archive':{k:v for k,v in result['archive'].items() if k!='checks'},'summary':result['summary'],'numbers':result['exact_numeric_registration'],'source_common_all_same':all(s['byte_identical'] for s in result['unchanged_source_reference_common']),'static_prefabs':statics},ensure_ascii=False,indent=2))
