// 保存每次imagegen真实输入；一个方向/动作一张编辑稿，绝不一次生成整个八向。
const fs=require('node:fs/promises'),path=require('node:path');
const root=__dirname;
const descriptions={down:'south, strictly front-facing',left:'west, side-facing screen left',up_left:'north-west, back three-quarter facing upper left',up:'north, strictly back-facing; no front face visible',up_right:'north-east, back three-quarter facing upper right',right:'east, side-facing screen right',down_right:'south-east, front three-quarter facing lower right'};
async function main(){
 for(const[direction,description]of Object.entries(descriptions))for(const action of['idle','collect']){
  const input=`source/action_edit_inputs_c2_rc01/${action}_${direction}.png`;
  await fs.mkdir(path.dirname(path.join(root,input)),{recursive:true});
  await fs.copyFile(path.join(root,`source/action-rig-batch/${action}/${direction}/edit_target_4x.png`),path.join(root,input));
  const idle=action==='idle';
  const prompt=`Use case: precise-object-edit.\nThe attached image is the exact EDIT TARGET, a ${idle?'one-row, two-column':'two-row, two-column'} pixel-art fixed-rig game animation, ${idle?'512x384, 4:3':'512x768, 2:3'} canvas. Each cell is 64x96 native pixels enlarged by nearest neighbor 4x. Preserve this exact grid, frame count, positions, scale, silhouettes and poses. Direction: ${description}.\nThis is a tiny mechanical-seam repair, not a redraw or a new animation. ${idle?'Idle: frame 0 is the original neutral stance and must remain identical. Frame 1 has the helmet/chest/shoulders/arms up exactly one native pixel while pelvis, legs and boots remain fixed. Repair only the small dark waist connection in frame 1. Do not alter any other area.':'Collect: read frames left to right then top to bottom. Frame 0 prepares, frame 1 crouches only two native pixels with its anatomical left wrist tool reaching modestly forward, frame 2 holds exactly the same body/leg/boot/far-arm pose while the tool arm adjusts slightly, frame 3 is the exact original neutral stance. Repair only dark shoulder/elbow and hip/knee/ankle connections of frames 0 to 2. Frame 3 remains identical. Frame 0 legs must stay identical to neutral. Where frames 1 and 2 have the same geometry, use exactly the same joint pixels.'}\nEvery armor shell, helmet, chest panel, forearm, hand, wrist tool and whole boot remains the same solid part from the source. Make overlaps readable and thick with a continuous blue-gray core. No full-width black cut through the limb, no isolated bright band, no detached pieces or thin connecting thread. Boots must retain their full original shape, flat sole, location and angle. Both feet remain planted. No toe bending, foot folding, extra shoe or extra armor plate. No wider crouch or longer reach. Do not add details, rearrange bright pixels, change lighting or mirror anything. Anatomical left wrist carries the small brass tool in every view. Fixed upper-left light. Cream armor, blue-gray core, restrained brass; hard square pixels and minimal palette.\nUse the target's exact empty margins and same canvas proportions. Transparent background with no glow, halo, shadow, checkerboard, floor, text, annotation or UI. Preserve all areas outside the tiny permitted connection seams exactly.\n`;
  await fs.writeFile(path.join(root,`prompts/${action}_${direction}_joint_edit_v011.txt`),['down','up'].includes(direction)?prompt.replace('crouches only two native pixels','crouches only one native pixel'):prompt);
 }
 console.log('Saved fourteen direction-specific prompts and exact edit inputs');
}
main().catch(error=>{console.error(error);process.exitCode=1;});
