
// 对比采用归一化动作相位，避免4帧和8帧待机因下标不同而错位。
const $=id=>document.getElementById(id);let clips=[],current,images={},elapsed=0,last=0,playing=true,light=false,lines=true,seamIndex=0;
const labels={'A-idle-down_right':'A · 右下待机','A-walk-down_right':'A · 右下行走','C-run-down_left':'C · 左下跑动'};
function loadImage(path){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error(path));img.src=path;});}
async function choose(){current=clips.find(c=>c.key===$('clip').value);playing=false;elapsed=0;images={};images.old=await loadImage('before/'+current.key+'.png');images.next=await loadImage(current.atlas);$('source').href=current.source;$('pose').href='poses/'+current.key+'.png';$('seamimg').src='qa/'+current.key+'-seam.png';$('contact').src='qa/'+current.key+'-contact.png';$('details').textContent=`${current.frame_count}帧 × ${current.duration_ms}ms。固定root (32,80)。本段状态：${current.visual_status}；${(current.issues||[]).join(" ")}`;playing=true;$('pause').textContent='暂停';draw();}
function drawOne(id,img,frame,offset=[0,0]){const ctx=$(id).getContext('2d');ctx.imageSmoothingEnabled=false;ctx.fillStyle=light?'#d4d9d4':'#182631';ctx.fillRect(0,0,384,384);ctx.drawImage(img,frame*64,0,64,96,(16+offset[0])*4,offset[1]*4,256,384);if(lines){ctx.strokeStyle=light?'#647b83':'#4d6470';ctx.beginPath();ctx.moveTo(192,0);ctx.lineTo(192,384);ctx.moveTo(0,320);ctx.lineTo(384,320);ctx.stroke();}}
function draw(){if(!current||!images.old||!images.next)return;const total=current.frame_count*current.duration_ms;const phase=(elapsed%total)/total;const n=Math.min(current.frame_count-1,Math.floor(phase*current.frame_count));const o=Math.min(current.old.frame_count-1,Math.floor(phase*current.old.frame_count));drawOne('old',images.old,o,current.old.draw_offsets?.[o]||[0,0]);drawOne('next',images.next,n);$('oldstate').textContent=`F${String(o).padStart(2,'0')} / ${current.old.frame_count}`;$('newstate').textContent=`F${String(n).padStart(2,'0')} / ${current.frame_count} · 已播放 ${Math.floor(elapsed/total)} 周期`;window.reviewState={key:current.key,frame:n,cycles:Math.floor(elapsed/total),playing};}
function tick(t){if(last&&playing)elapsed+=(t-last)*Number($('speed').value);last=t;draw();requestAnimationFrame(tick)}
$('clip').onchange=()=>choose().catch(e=>$('details').textContent=e.message);$('pause').onclick=()=>{playing=!playing;$('pause').textContent=playing?'暂停':'继续';};$('step').onclick=()=>{playing=false;$('pause').textContent='继续';elapsed=(Math.floor(elapsed/current.duration_ms)+1)*current.duration_ms;draw();};$('seam').onclick=()=>{playing=false;$('pause').textContent='继续';const fs=[current.frame_count-2,current.frame_count-1,0,1];elapsed=fs[seamIndex++%4]*current.duration_ms;draw();};$('bg').onclick=()=>{light=!light;draw();};$('guides').onclick=()=>{lines=!lines;$('guides').textContent='辅助线：'+(lines?'开':'关');draw();};
fetch('catalog.json').then(r=>r.json()).then(async data=>{clips=data.clips;for(const c of clips){const option=document.createElement('option');option.value=c.key;option.textContent=labels[c.key];$('clip').append(option)}await choose();requestAnimationFrame(tick)}).catch(e=>$('details').textContent='加载失败：'+e.message);
